# Generated by Django 3.2.5 on 2021-07-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Movie',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='pub_date',
            new_name='release_date',
        ),
    ]
