# Generated by Django 3.2.5 on 2021-07-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.CharField(default=0.0005, max_length=200),
            preserve_default=False,
        ),
    ]
